/**
 * Fetches CODESIGN Tistory RSS and writes src/data/posts.js
 * Usage: node scripts/sync-blog.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const RSS_URL = "https://codesign.tistory.com/rss";
const BLOG_URL = "https://codesign.tistory.com/";
const LIMIT = 8;
const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/data/posts.js");

function decodeEntities(text) {
  return text
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&ldquo;|&rdquo;/g, '"')
    .replace(/&lsquo;|&rsquo;/g, "'")
    .replace(/&mdash;/g, "—")
    .replace(/&ndash;/g, "–")
    .replace(/&rarr;/g, "→")
    .replace(/&amp;/g, "&")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCharCode(parseInt(h, 16)));
}

function stripTags(html) {
  return decodeEntities(html)
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function tag(block, name) {
  const cdata = block.match(new RegExp(`<${name}><!\\[CDATA\\[([\\s\\S]*?)\\]\\]><\\/${name}>`));
  if (cdata) return cdata[1].trim();
  const plain = block.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`));
  return plain ? decodeEntities(plain[1].trim()) : "";
}

function parseItems(xml) {
  const items = [];
  const re = /<item>([\s\S]*?)<\/item>/g;
  let m;
  while ((m = re.exec(xml))) {
    const block = m[1];
    const title = tag(block, "title");
    const link = tag(block, "link");
    const pubDate = tag(block, "pubDate");
    const description = tag(block, "description");
    if (!title || !link) continue;

    const excerpt = stripTags(description).slice(0, 140);
    items.push({
      title: title.replace(/\\/g, ""),
      link,
      date: pubDate ? new Date(pubDate).toISOString().slice(0, 10) : "",
      excerpt: excerpt.length >= 140 ? `${excerpt}…` : excerpt,
    });
  }
  return items;
}

const res = await fetch(RSS_URL);
if (!res.ok) throw new Error(`RSS fetch failed: ${res.status}`);
const xml = await res.text();
const posts = parseItems(xml).slice(0, LIMIT);

mkdirSync(dirname(OUT), { recursive: true });
const body = `/** Auto-generated by scripts/sync-blog.mjs — do not edit by hand */
export const blogUrl = ${JSON.stringify(BLOG_URL)};

export const posts = ${JSON.stringify(posts, null, 2)};
`;
writeFileSync(OUT, body, "utf8");
console.log(`Wrote ${posts.length} posts → src/data/posts.js`);
